# Generated by Django 2.1.4 on 2018-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
            ],
        ),
    ]
