# Generated by Django 2.1.4 on 2018-12-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplay', '0002_buffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buffer',
        ),
    ]
